name: Build Packer on Merge

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  build-packer:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven
      - name: Build Maven
        run: |
          mvn clean package
          pwd
          mkdir stage && cp target/webapp-0.0.1-SNAPSHOT.jar stage   
          cp stage/*.jar ami
          cd ami && ls -all
      - name: Packer build
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: "-color=false -on-error=abort"
          target: main.pkr.hcl
          working_directory: ami
        env:
          PACKER_LOG: 1 # enable debug log for packer
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
